-- CreateTable
CREATE TABLE "about_page" (
    "id" TEXT NOT NULL DEFAULT 'about',
    "seoTitle" TEXT,
    "seoDescription" TEXT,
    "seoKeywords" TEXT,
    "ogImage" TEXT,
    "bannerImage" TEXT,
    "bannerTitle" TEXT,
    "bannerSubtitle" TEXT,
    "breadcrumbTitle" TEXT,
    "introTitle" TEXT,
    "introEyebrow" TEXT,
    "introHtml" TEXT,
    "introImage" TEXT,
    "missionTitle" TEXT,
    "missionHtml" TEXT,
    "visionTitle" TEXT,
    "visionHtml" TEXT,
    "whyChooseTitle" TEXT,
    "whyChooseHtml" TEXT,
    "values" JSONB,
    "stats" JSONB,
    "timeline" JSONB,
    "features" JSONB,
    "certifications" JSONB,
    "industries" JSONB,
    "ctaTitle" TEXT,
    "ctaText" TEXT,
    "ctaButtonLabel" TEXT,
    "ctaButtonHref" TEXT,
    "status" "PageStatus" NOT NULL DEFAULT 'PUBLISHED',
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "about_page_pkey" PRIMARY KEY ("id")
);
